Fixed #39 patch and improved formatting (doc unfinished)
- hard-coded assert or fail function name

  The FUNCNAME is not portable, which probably only works for Bash.

- ${SHUNIT_REPORT_SKIP}

  Also read from environment variable.

- parameters to assert or fail function call

  The parameters -- including message -- are displayed in the similar
  fashion as assert failed messages, for examples:

    ASSERT:expected:<foo> but was:<bar>
    SKIPPED:assertEquals <foo> <bar>

    ASSERT:message expected:<foo> but was:<bar>
    SKIPPED:assertEquals <message> <foo> <bar>

  "SKIPPED:" are in yellow.

- include line number when available

  If the assert or fail function is called via macros such as
  _ASSERT_EQUALS_, which includes line number, then the number will also
  be shown in the skipping messages, for example:

    ASSERT:[110]  expected:<foo> but was:<bar>
    SKIPPED:[123] assertEquals <foo> <bar>

- fatal if assert or fail function name is not supplied to functions
  _shunit_shouldSkip and _shunit_assertSkip